title: Anh-Duy Vu
email: vuanhduy1809@gmail.com
description: This is a personal blog of Anh-Duy Vu
url: "https://vuanhduy.github.io" # the base hostname & protocol for your site
author: Anh-Duy Vu
avatar: /logo.png
email: vuanhduy1809@gmail.com
location: Onatrio, Canada

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate
  - jemoji

include:
  - _pages

exclude:
  - scripts/
  - README.md

defaults:
  - scope:
      path: ""      
      type: "posts"
    values:
      layout: "post"
      author: "Anh-Duy Vu"
      image: "logo.png"
      share: true
  - scope:
      path: ""      
      type: "pages"
    values:
      layout: "page"
      author: "Anh-Duy Vu"
      image: "logo.png"

remote_theme: ngzhio/jekyll-theme-hamilton

paginate: 10
