title: Anh-Duy Vu
description: Anh-Duy's blog
url: https://vuanhduy.github.io
author: Anh-Duy Vu
avatar: /avatar.png
email: vuanhduy1809@gmail.com
location: Hamilton, ON, Canada

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-spaceship
  - jemoji

include:
  - _pages

exclude:
  - scripts/
  - README.md

permalink: /:year/:month/:day/:title.html

defaults:
  - scope:
      path: ""      
      type: "posts"
    values:
      layout: "post"
      author: "Anh-Duy Vu"
      image: "avatar.png"
      share: true
  - scope:
      path: ""      
      type: "pages"
    values:
      layout: "page"
      author: "Anh-Duy Vu"
      image: "avatar.png"

# Jekyll Remote Theme
# ===================
remote_theme: ngzhio/jekyll-theme-hamilton

# Jekyll SEO Tag (Optional)
# =========================
logo: avatar.jpg
social:
  name: Anh-Duy Vu
  links:
    - https://github.com/vuanhduy
lang: en

# Jekyll Paginate
# ===============
paginate: 10
