title: Anh-Duy Vu
email: vuanhduy1809@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://vuanhduy.github.io" # the base hostname & protocol for your site
author: Anh-Duy Vu
avatar: /logo.png
email: vuanhduy1809@gmail.com
location: Onatrio, Canada
github_username:  vuanhduy

# Build settings
# markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate
  - jemoji

include:
  - _pages

exclude:
  - scripts/
  - README.md

remote_theme: ngzhio/jekyll-theme-hamilton

logo: logo.png
paginate: 10
skin: Sunset
